export const getInputFields = (
  albumData,
  handleChange,
  handleFileChange,
  errors,
) => [
  {
    label: "Album Name",
    id: "formAlbumName",
    name: "album_name",
    type: "text",
    value: albumData.album_name,
    onChange: handleChange,
    error: errors.album_name,
  },
  {
    label: "Artist Name",
    id: "formArtistName",
    name: "artist_name",
    type: "text",
    value: albumData.artist_name,
    onChange: handleChange,
    error: errors.artist_name,
  },
  {
    label: "Year of Release",
    id: "formYearOfRelease",
    name: "year_of_release",
    type: "number",
    value: albumData.year_of_release,
    onChange: handleChange,
    error: errors.year_of_release,
  },
  {
    label: "Ranking",
    id: "formRanking",
    name: "ranking",
    type: "number",
    value: albumData.ranking,
    onChange: handleChange,
    error: errors.ranking,
    // min: '1',
    // max: '5',
  },
  {
    label: "Genre",
    id: "formGenre",
    name: "genre",
    type: "select",
    value: albumData.genre,
    onChange: handleChange,
    options: [
      { label: "Jazz", value: "jazz" },
      { label: "Rock", value: "rock" },
      { label: "Pop", value: "pop" },
      { label: "Classical", value: "classical" },
      { label: "Hip-Hop", value: "hip-Hop" },
    ],
    error: errors.genre,
  },
  {
    label: "Description",
    id: "formDescription",
    name: "description",
    type: "textarea",
    value: albumData.description,
    onChange: handleChange,
    error: errors.description,
  },
  {
    label: "Album Cover",
    id: "formAlbumCover",
    name: "album_cover",
    type: "file",
    value: albumData.album_cover,
    onChange: handleFileChange,
    error: errors.album_cover,
  },
];
